#Define numpy:
Numpy is python library pakage Numpy is a general-purpose array-processing package. 
It provides a high-performance multidimensional array object, and tools for working with these arrays.

In [20]:
#creating some arrays using numpy
import numpy as np
x = np.array([1,2,3])#single dimension
y = np.array([(1,2,3),(4,5,6)])#2 D dimension 
z = np.array([(1,2,3),(4,5,6),(7,8,9)])#(3d matrix)
n = np.array([(1.1,1.2,1.3),(3,4,5),(12.5,6.7,8.9),(7,8,9)])
n = np.array([(1.1,1.2,1.3),(3,4,5),(12.5,6.7,8.9),(7,8,9)],dtype = int)
n = np.array([(1.1,1.2,1.3,5),(3,4,5,5),(12.5,6.7,8.9,5),(7,8,9,5)],dtype = float)#ndimension
print(x)
print(y)
print(z)
print(n)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1.1  1.2  1.3  5. ]
 [ 3.   4.   5.   5. ]
 [12.5  6.7  8.9  5. ]
 [ 7.   8.   9.   5. ]]


In [10]:

import numpy as sai
x = sai.zeros(2,dtype =float)
print(x,type(x))
y = sai.ones(1,dtype=int)
z = sai.ones((2,2,4,8),dtype = float)#(no of shapes,no of dimensions,no of rows ,no of coulmns)
m = sai.ones((3,4),dtype = float)#nof rows,no of columns
n =sai.ones
print(y)
print(z)
print(m,type(m))


[0. 0.] <class 'numpy.ndarray'>
[1]
[[[[1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]]]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] <class 'numpy.ndarray'>


In [26]:
#generating the 6by 6 matrix using 3d array
import numpy as sai
y = sai.zeros((6,6,6))
z = y[:,:,1]
print(x)
print(y)

[[[0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]]]
[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]


In [74]:
#printing the 0s and 1s in 1d, 2d,3d
import numpy as np
a = np.zeros(4,dtype = int)#1d array with 0's
print(a)
b = np.zeros((1,6),dtype = int)
print(b)
c = np.zeros((1,2,3),dtype = int)
print(c)
a = np.ones(4,dtype = int)#1d array with 1's
print(a)
b = np.ones((1,6),dtype = int)#2d array with 1's
print(b)
c = np.ones((1,2,3),dtype = int)#3d array with 1's
print(c)



[0 0 0 0]
[[0 0 0 0 0 0]]
[[[0 0 0]
  [0 0 0]]]
[1 1 1 1]
[[1 1 1 1 1 1]]
[[[1 1 1]
  [1 1 1]]]


In [132]:
#Evenly spaced
import numpy as np
x = np.arange(0,11,2)
print(x)
y = np.arange(0,120, 2)
print(y)
#Evenly spaced with 2d array

p = np.arange(0,11,2).reshape(2,3)
print(p)

#Evenly spaced with 3d array
q = np.arange(0,11,2).reshape(2,3)
print(q)

[ 0  2  4  6  8 10]
[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118]
[[ 0  2  4]
 [ 6  8 10]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [135]:
#odd Spaced
import numpy as np
x = np.arange(1,21,2)
print(x)
n = np.arange(1,120,2)   #1d array
print(n)

#Odd spaced in 2d

i = np.arange(1,25,2).reshape(3,4)
print(i)


[ 1  3  5  7  9 11 13 15 17 19]
[  1   3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35
  37  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71
  73  75  77  79  81  83  85  87  89  91  93  95  97  99 101 103 105 107
 109 111 113 115 117 119]
[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]


In [143]:
#combination of evenly spaced and odd spaced
import numpy as np
x = np.arange(0,23,3)
print(x)

#combination of evenly and odd spaced values
y = np.arange(0,23,3).reshape(2,4)
print(y)
#combination of evenly and odd spaced values

q  = np.arange(0,24,1).reshape(2,3,4)
print(q)

[ 0  3  6  9 12 15 18 21]
[[ 0  3  6  9]
 [12 15 18 21]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
